In [3]:
from tensorflow.keras.preprocessing.text import one_hot


In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Define the vocabulary size
voc_size=10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### One Hot Representation 
#this function convert each word into number from 1 to voc_size

one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9562, 9857, 9247, 736],
 [9562, 9857, 9247, 4194],
 [9562, 2863, 9247, 476],
 [3517, 565, 8183, 7536, 3574],
 [3517, 565, 8183, 7536, 287],
 [4600, 9562, 2404, 9247, 3755],
 [2167, 9618, 6426, 7536]]

In [13]:
## word Embedding Representation
import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
#sentence is about 4-5words so we will take max length of 8
#by pad we add 0s in the beginning of the sentence
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9562 9857 9247  736]
 [   0    0    0    0 9562 9857 9247 4194]
 [   0    0    0    0 9562 2863 9247  476]
 [   0    0    0 3517  565 8183 7536 3574]
 [   0    0    0 3517  565 8183 7536  287]
 [   0    0    0 4600 9562 2404 9247 3755]
 [   0    0    0    0 2167 9618 6426 7536]]


In [15]:
## feature representation
dim=10

In [ ]:
#make model then make embedding layer of each other has dimension 10 
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

2025-07-07 00:04:23.210105: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2025-07-07 00:04:23.210425: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2025-07-07 00:04:23.210441: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2025-07-07 00:04:23.210677: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-07-07 00:04:23.211036: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 188ms/step


2025-07-07 00:04:46.938179: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


array([[[ 0.00799055,  0.04513103,  0.00861903, -0.03480575,
          0.02599793,  0.04967662, -0.02715921, -0.00207939,
          0.00979821, -0.02109047],
        [ 0.00799055,  0.04513103,  0.00861903, -0.03480575,
          0.02599793,  0.04967662, -0.02715921, -0.00207939,
          0.00979821, -0.02109047],
        [ 0.00799055,  0.04513103,  0.00861903, -0.03480575,
          0.02599793,  0.04967662, -0.02715921, -0.00207939,
          0.00979821, -0.02109047],
        [ 0.00799055,  0.04513103,  0.00861903, -0.03480575,
          0.02599793,  0.04967662, -0.02715921, -0.00207939,
          0.00979821, -0.02109047],
        [-0.04375284,  0.0153186 , -0.04902879, -0.0241981 ,
          0.0439905 , -0.04895581, -0.03048624, -0.0069445 ,
         -0.01028299,  0.04380448],
        [ 0.02189067, -0.02225592, -0.04372809, -0.02163421,
         -0.0267959 , -0.0123558 , -0.04875612, -0.01171782,
          0.00261622,  0.02663953],
        [-0.04753734, -0.009737  ,  0.00201686,  0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 9562, 9857, 9247,  736], dtype=int32)

In [20]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 94ms/step


array([[ 0.00799055,  0.04513103,  0.00861903, -0.03480575,  0.02599793,
         0.04967662, -0.02715921, -0.00207939,  0.00979821, -0.02109047],
       [ 0.00799055,  0.04513103,  0.00861903, -0.03480575,  0.02599793,
         0.04967662, -0.02715921, -0.00207939,  0.00979821, -0.02109047],
       [ 0.00799055,  0.04513103,  0.00861903, -0.03480575,  0.02599793,
         0.04967662, -0.02715921, -0.00207939,  0.00979821, -0.02109047],
       [ 0.00799055,  0.04513103,  0.00861903, -0.03480575,  0.02599793,
         0.04967662, -0.02715921, -0.00207939,  0.00979821, -0.02109047],
       [-0.04375284,  0.0153186 , -0.04902879, -0.0241981 ,  0.0439905 ,
        -0.04895581, -0.03048624, -0.0069445 , -0.01028299,  0.04380448],
       [ 0.02189067, -0.02225592, -0.04372809, -0.02163421, -0.0267959 ,
        -0.0123558 , -0.04875612, -0.01171782,  0.00261622,  0.02663953],
       [-0.04753734, -0.009737  ,  0.00201686,  0.00527543, -0.04325515,
         0.03476986,  0.02614787,  0.02086438